### ISSUE TITLE
usbMIDI2CV_MC.ino.hex is outdated

### ISSUE THREAD

**Issue by Fisico** [elkayem/usbMIDI2CV_MC#2]
Hi,

FYI
usbMIDI2CV_MC.ino.hex is outdated the OLED Display is not working. I self compiled the latest version with your ino file... that is working great. The hex file is 6 months older.

**Comment by elkayem** [comment]
David, thank you for pointing that out!  I had failed to update the hex file.  I just posted an update.  If you could, would you mind testing the hex file out on your end to make sure it is working.  I also updated the call to Adafruit_SSD1306 display to be consistent with the latest Adafruit library.

**Comment by Fisico** [comment]
thank you for the fast response... i will test it tomorrow. And a very big thank you for sharing this awesome project with the world.

**Comment by Fisico** [comment]
@elkayem 
sorry for the delay.... tested it today with the new hex file and all is working great. Thank you.

**Comment by elkayem** [comment]
Thanks for testing that out!  I'm going to close out this issue.
