### ISSUE TITLE
Glide/Portamento Feature 

### ISSUE THREAD

**Issue by Fisico** [elkayem/usbMIDI2CV_MC#3]
Hi,
is it possible to implement "Glide/Portamento"? 
It could be controlled with the encoder.

**Comment by Fisico** [comment]
@elkayem 
Any update on this feature request?
I really like the converter but Glide/Portamento is missing. Many commercial products are having this feature. But most of them are only single voice and 3 voices are very nice....

**Comment by elkayem** [comment]
Hi Fisico, this sounds like a good feature. If someone were to make a good implementation of this, I would certainly merge it into the code. Closing this issue because it really isn't an issue.
